version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
          interval: "weekly"
          # Check for npm updates at 9am UTC
          time: "09:00"
    open-pull-requests-limit: 10
    versioning-strategy: increase